name: cesiumjs-anywidget-examples
channels:
  - https://repo.prefix.dev/emscripten-forge-4x
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python # A Jupyter kernel for Python
  - sidecar
  - numpy
  - scipy
  - pillow
  - pyyaml
  - pip: # List pure Python packages from PyPi here
    - cesiumjs-anywidget
    